-- GENERATED by scripts/generate-seed-sql.mjs from src/lib/seed.js. Do not edit by hand.
-- FICTIONAL demo community for Kitside. Every person, activity and post below is made up.
-- Places mentioned are examples only and are not affiliated with or endorsed by Kitside.
-- Run after supabase/migrations/*_kitside_init.sql.
-- NON-DESTRUCTIVE: only inserts rows that aren't there yet (on conflict do nothing).
-- It never deletes or changes existing rows, so it's safe to run more than once.
-- To hide all example content later, set VITE_SHOW_DEMO=false (no database change needed).

begin;

insert into public.profiles (id, name, role, title, bio, neighbourhood, interests, looking_for, working_on, is_remote, avatar_hue, is_demo) values
  ('00000000-0000-4000-8000-000000000001', 'Maya Okafor', 'Design', 'Product designer', 'Designs for screen readers first and everyone else second. Thursday nights she’s at the pottery wheel, usually losing.', 'Kitsilano', array['Running','Ceramics','Coffee','Design']::text[], array['Collaborators','Fitness buddies','Meet people']::text[], 'Accessibility tools for small web teams', true, 18, true),
  ('00000000-0000-4000-8000-000000000002', 'Daniel Reyes', 'Engineering', 'Software engineer', 'Writes Rust for a Berlin company from a desk that faces the water. Bikes to Spanish Banks most mornings before standup.', 'Kits Point', array['Cycling','Cooking','Startups','Outdoors']::text[], array['Side projects','Coworking']::text[], 'Open-source tools for climate datasets', true, 200, true),
  ('00000000-0000-4000-8000-000000000003', 'Rachel Kim', 'Founder', 'Founder', 'Second company. Consumer health, a team of four, and strong opinions about sleep. Takes most meetings as walks.', 'Kitsilano', array['Tennis','Reading','Coffee walks']::text[], array['Meet people','Mentors']::text[], 'A sleep coaching app', false, 340, true),
  ('00000000-0000-4000-8000-000000000004', 'Sam Whitford', 'Product', 'Product manager', 'PM on AI tools for teachers. Will talk about your favourite West 4th restaurant for an unreasonable amount of time.', 'Fairview', array['Running','Music','Restaurants','AI']::text[], array['Meet people','Friends','Events']::text[], 'AI tools for classrooms', true, 265, true),
  ('00000000-0000-4000-8000-000000000005', 'Jon Takahashi', 'Creative', 'Creative director, independent studio', 'Runs a two-person studio out of the garage behind his place. Surfs Tofino when the swell is right and Jericho when it isn’t.', 'Kits Point', array['Photography','Surfing','Music']::text[], array['Collaborators','Meet people']::text[], 'A photo book about the Fraser River', false, 32, true),
  ('00000000-0000-4000-8000-000000000006', 'Priya Nair', 'Product', 'Product manager, AI education', 'Climbs three nights a week and is trying to learn Portuguese before a trip in the spring. Ask her for a trail recommendation.', 'West Point Grey', array['Running','Climbing','Learning','Outdoors']::text[], array['Fitness buddies','Mentors','Friends']::text[], 'Adaptive lessons for adult learners', false, 150, true),
  ('00000000-0000-4000-8000-000000000007', 'Ethan Liu', 'Engineering', 'Machine learning engineer', 'Works on medical imaging by day. Cooks one ambitious dinner a week and needs people to help eat it.', 'Fairview', array['Cooking','AI','Cycling','Food']::text[], array['Friends','Side projects']::text[], 'A tiny app for splitting grocery runs', false, 225, true),
  ('00000000-0000-4000-8000-000000000008', 'Leah Bergström', 'Marketing', 'Growth marketer, freelance', 'Helps early-stage companies find their first thousand customers. Moved from Stockholm two years ago and is still hunting for a proper cardamom bun.', 'Kitsilano', array['Tennis','Books','Food']::text[], array['Meet people','Coworking','Collaborators']::text[], 'A newsletter about consumer growth', true, 48, true),
  ('00000000-0000-4000-8000-000000000009', 'Marcus Bell', 'Operations', 'Operations lead', 'Keeps a logistics startup running and coaches U10 soccer on Saturdays. Wants a weekday running crew that doesn’t start at 5 a.m.', 'Arbutus Ridge', array['Running','Soccer','Coffee','Fitness']::text[], array['Fitness buddies','Mentors']::text[], 'Learning to build with no-code tools', false, 5, true),
  ('00000000-0000-4000-8000-000000000010', 'Ana Sousa', 'Other', 'Physiotherapist', 'Not in tech, just curious about it. Runs a small clinic three days a week and moved here from Lisbon in August.', 'Kitsilano', array['Outdoors','Swimming','Learning']::text[], array['Meet people','Friends','Events']::text[], '', false, 300, true),
  ('00000000-0000-4000-8000-000000000011', 'Tom Hargreaves', 'Founder', 'Founder, bootstrapped', 'Twelve years in enterprise sales, now building software for independent bike shops. Fixes his own bikes, badly.', 'Dunbar', array['Cycling','Startups','Coffee']::text[], array['Collaborators','Mentors']::text[], 'Inventory software for bike shops', false, 120, true),
  ('00000000-0000-4000-8000-000000000012', 'Grace Chen', 'Design', 'UX researcher', 'Interviews people for a living, so expect follow-up questions. Sea swims at Kits year-round, including January.', 'Fairview', array['Swimming','Design','Food']::text[], array['Side projects','Meet people']::text[], 'A field guide to running user interviews', true, 185, true),
  ('00000000-0000-4000-8000-000000000013', 'Noah Friedman', 'Creative', 'Composer and audio engineer', 'Scores indie games from a converted laundry room. Looking for people who want to play music on Sunday afternoons.', 'West Point Grey', array['Music','Outdoors','AI']::text[], array['Collaborators','Friends']::text[], 'The soundtrack for a small puzzle game', true, 280, true),
  ('00000000-0000-4000-8000-000000000014', 'Isla MacLeod', 'Engineering', 'Engineering manager', 'Manages a team spread over four time zones, which mostly means very early coffee. Training for the spring half marathon.', 'Kitsilano', array['Running','Coffee','Learning']::text[], array['Coworking','Fitness buddies','Meet people']::text[], 'Nothing on the side right now, and enjoying it', true, 95, true)
on conflict (id) do nothing;

insert into public.activities (id, host_id, title, description, category, location, starts_at, is_demo) values
  ('00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000014', 'Morning run', 'Easy-paced 5K out and back along the water. No pressure, no watches required. Coffee after for anyone who wants it.', 'Move', 'Point Grey Road', ((date_trunc('day', now() at time zone 'America/Vancouver')
      + (((6 - extract(dow from now() at time zone 'America/Vancouver')::int) + 7) % 7) * interval '1 day'
      + time '09:00') at time zone 'America/Vancouver'), true),
  ('00000000-0000-4000-8000-000000000102', '00000000-0000-4000-8000-000000000002', 'Build together', 'Bring a side project and work alongside a few other people for the morning. Quiet table, headphones welcome.', 'Work', 'A café on West 4th', ((date_trunc('day', now() at time zone 'America/Vancouver')
      + (((3 - extract(dow from now() at time zone 'America/Vancouver')::int) + 7) % 7) * interval '1 day'
      + time '10:00') at time zone 'America/Vancouver'), true),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000004', 'Product people dinner', 'Casual dinner for people who work in or around product. No decks, no pitches. Spot shared with those who say they’re in.', 'Eat', 'Kitsilano', ((date_trunc('day', now() at time zone 'America/Vancouver')
      + (((4 - extract(dow from now() at time zone 'America/Vancouver')::int) + 7) % 7) * interval '1 day'
      + time '19:00') at time zone 'America/Vancouver'), true),
  ('00000000-0000-4000-8000-000000000104', '00000000-0000-4000-8000-000000000009', 'Outdoor bootcamp', 'A friendly community workout on the grass. Every level welcome. Bring water and something to lie on.', 'Move', 'Kits Beach park', ((date_trunc('day', now() at time zone 'America/Vancouver')
      + (((0 - extract(dow from now() at time zone 'America/Vancouver')::int) + 7) % 7) * interval '1 day'
      + time '11:00') at time zone 'America/Vancouver'), true),
  ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000011', 'Side project night', 'Bring whatever you’re building, even if it’s a spreadsheet. Five-minute show-and-tell, then heads down.', 'Build', 'Kitsilano', ((date_trunc('day', now() at time zone 'America/Vancouver')
      + (((4 - extract(dow from now() at time zone 'America/Vancouver')::int) + 7) % 7) * interval '1 day'
      + time '18:30') at time zone 'America/Vancouver'), true),
  ('00000000-0000-4000-8000-000000000106', '00000000-0000-4000-8000-000000000012', 'Sunset sea swim', 'A short dip and a long shiver. Wetsuits welcome, bravado optional. We stick close to shore.', 'Move', 'Kits Beach', ((date_trunc('day', now() at time zone 'America/Vancouver')
      + (((2 - extract(dow from now() at time zone 'America/Vancouver')::int) + 7) % 7) * interval '1 day'
      + time '18:15') at time zone 'America/Vancouver'), true),
  ('00000000-0000-4000-8000-000000000107', '00000000-0000-4000-8000-000000000003', 'Coffee walk along the seawall', 'Grab a coffee, walk the water, talk about whatever. A good one if you’re new around here.', 'Social', 'Kits Point to Vanier Park', ((date_trunc('day', now() at time zone 'America/Vancouver')
      + (((0 - extract(dow from now() at time zone 'America/Vancouver')::int) + 7) % 7) * interval '1 day'
      + time '08:30') at time zone 'America/Vancouver'), true),
  ('00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000006', 'Pacific Spirit trail walk', 'About 90 minutes on the forest trails at a chatty pace. We’ll meet at a trailhead off West 16th.', 'Explore', 'Pacific Spirit Regional Park', ((date_trunc('day', now() at time zone 'America/Vancouver')
      + (((6 - extract(dow from now() at time zone 'America/Vancouver')::int) + 7) % 7) * interval '1 day'
      + time '10:30') at time zone 'America/Vancouver'), true),
  ('00000000-0000-4000-8000-000000000109', '00000000-0000-4000-8000-000000000013', 'Sunday jam', 'Bring an instrument or don’t. Mostly folk and whatever someone can carry. Snacks provided by whoever remembers.', 'Social', 'West Point Grey', ((date_trunc('day', now() at time zone 'America/Vancouver')
      + (((0 - extract(dow from now() at time zone 'America/Vancouver')::int) + 7) % 7) * interval '1 day'
      + time '15:00') at time zone 'America/Vancouver'), true)
on conflict (id) do nothing;

insert into public.announcements (id, author_id, title, details, category, location, happens_at, is_demo, created_at) values
  ('00000000-0000-4000-8000-000000000201', '00000000-0000-4000-8000-000000000014', 'Anyone up for a run Saturday morning?', 'Thinking Point Grey Road around 9. Easy pace, coffee after.', 'Move', 'Point Grey Road', time '09:00', true, now() - interval '3 hours'),
  ('00000000-0000-4000-8000-000000000202', '00000000-0000-4000-8000-000000000011', 'Looking for a designer', 'I’m building inventory software for independent bike shops and would love to find someone who wants to explore it with me. Coffee on me while we figure out if it’s a fit.', 'Build', '', null, true, now() - interval '9 hours'),
  ('00000000-0000-4000-8000-000000000203', '00000000-0000-4000-8000-000000000002', 'Anyone working from somewhere tomorrow?', 'Thinking a café on West 4th around 10. Quiet table, headphones optional.', 'Work', 'A café on West 4th', time '10:00', true, now() - interval '20 hours'),
  ('00000000-0000-4000-8000-000000000204', '00000000-0000-4000-8000-000000000008', 'Anyone interested in a side-project night?', 'A few of us are thinking Thursday evening. Bring whatever you’re building.', 'Build', 'Kitsilano', null, true, now() - interval '28 hours'),
  ('00000000-0000-4000-8000-000000000205', '00000000-0000-4000-8000-000000000010', 'New to Kits and would love a walking group', 'Moved here from Lisbon in August. Free most evenings after 6 and happy to walk anywhere near the water.', 'Social', 'Kitsilano', null, true, now() - interval '34 hours'),
  ('00000000-0000-4000-8000-000000000206', '00000000-0000-4000-8000-000000000012', 'Looking for 5 people to chat with about finding things to do locally', 'Twenty minutes over coffee, and I’m buying. It’s for a side project, not a company.', 'Build', '', null, true, now() - interval '52 hours'),
  ('00000000-0000-4000-8000-000000000207', '00000000-0000-4000-8000-000000000007', 'Making far too much curry on Sunday', 'Big pot of chicken curry. Room for four at the table. Bring a dessert, or just yourself.', 'Eat', 'Fairview', null, true, now() - interval '70 hours'),
  ('00000000-0000-4000-8000-000000000208', '00000000-0000-4000-8000-000000000006', 'Climbing partner wanted', 'Bouldering Tuesday and Thursday evenings. Beginner-friendly. I’m not great either.', 'Move', '', null, true, now() - interval '96 hours'),
  ('00000000-0000-4000-8000-000000000209', '00000000-0000-4000-8000-000000000003', 'Happy to give feedback on your pitch', 'Second-time founder. Thirty minutes on a coffee walk, no strings. Especially keen to help anyone doing consumer health.', 'Build', 'Kitsilano', null, true, now() - interval '120 hours'),
  ('00000000-0000-4000-8000-000000000210', '00000000-0000-4000-8000-000000000013', 'Looking for a drummer, any level', 'Very casual Sunday afternoon jams. We play loudly and not especially well.', 'Social', 'West Point Grey', null, true, now() - interval '150 hours')
on conflict (id) do nothing;

insert into public.activity_interests (activity_id, profile_id) values
  ('00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000001'),
  ('00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000004'),
  ('00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000006'),
  ('00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000009'),
  ('00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000012'),
  ('00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000003'),
  ('00000000-0000-4000-8000-000000000102', '00000000-0000-4000-8000-000000000008'),
  ('00000000-0000-4000-8000-000000000102', '00000000-0000-4000-8000-000000000013'),
  ('00000000-0000-4000-8000-000000000102', '00000000-0000-4000-8000-000000000011'),
  ('00000000-0000-4000-8000-000000000102', '00000000-0000-4000-8000-000000000001'),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000001'),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000003'),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000006'),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000008'),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000011'),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000012'),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000014'),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000007'),
  ('00000000-0000-4000-8000-000000000104', '00000000-0000-4000-8000-000000000010'),
  ('00000000-0000-4000-8000-000000000104', '00000000-0000-4000-8000-000000000014'),
  ('00000000-0000-4000-8000-000000000104', '00000000-0000-4000-8000-000000000006'),
  ('00000000-0000-4000-8000-000000000104', '00000000-0000-4000-8000-000000000003'),
  ('00000000-0000-4000-8000-000000000104', '00000000-0000-4000-8000-000000000004'),
  ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000002'),
  ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000005'),
  ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000007'),
  ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000008'),
  ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000012'),
  ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000013'),
  ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000001'),
  ('00000000-0000-4000-8000-000000000106', '00000000-0000-4000-8000-000000000010'),
  ('00000000-0000-4000-8000-000000000106', '00000000-0000-4000-8000-000000000005'),
  ('00000000-0000-4000-8000-000000000106', '00000000-0000-4000-8000-000000000003'),
  ('00000000-0000-4000-8000-000000000107', '00000000-0000-4000-8000-000000000010'),
  ('00000000-0000-4000-8000-000000000107', '00000000-0000-4000-8000-000000000008'),
  ('00000000-0000-4000-8000-000000000107', '00000000-0000-4000-8000-000000000004'),
  ('00000000-0000-4000-8000-000000000107', '00000000-0000-4000-8000-000000000011'),
  ('00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000013'),
  ('00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000010'),
  ('00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000007'),
  ('00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000014'),
  ('00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000002'),
  ('00000000-0000-4000-8000-000000000109', '00000000-0000-4000-8000-000000000005'),
  ('00000000-0000-4000-8000-000000000109', '00000000-0000-4000-8000-000000000004'),
  ('00000000-0000-4000-8000-000000000109', '00000000-0000-4000-8000-000000000012')
on conflict do nothing;

insert into public.announcement_interests (announcement_id, profile_id) values
  ('00000000-0000-4000-8000-000000000201', '00000000-0000-4000-8000-000000000009'),
  ('00000000-0000-4000-8000-000000000201', '00000000-0000-4000-8000-000000000001'),
  ('00000000-0000-4000-8000-000000000201', '00000000-0000-4000-8000-000000000006'),
  ('00000000-0000-4000-8000-000000000202', '00000000-0000-4000-8000-000000000001'),
  ('00000000-0000-4000-8000-000000000202', '00000000-0000-4000-8000-000000000012'),
  ('00000000-0000-4000-8000-000000000203', '00000000-0000-4000-8000-000000000008'),
  ('00000000-0000-4000-8000-000000000203', '00000000-0000-4000-8000-000000000014'),
  ('00000000-0000-4000-8000-000000000203', '00000000-0000-4000-8000-000000000013'),
  ('00000000-0000-4000-8000-000000000203', '00000000-0000-4000-8000-000000000004'),
  ('00000000-0000-4000-8000-000000000204', '00000000-0000-4000-8000-000000000002'),
  ('00000000-0000-4000-8000-000000000204', '00000000-0000-4000-8000-000000000007'),
  ('00000000-0000-4000-8000-000000000204', '00000000-0000-4000-8000-000000000011'),
  ('00000000-0000-4000-8000-000000000204', '00000000-0000-4000-8000-000000000005'),
  ('00000000-0000-4000-8000-000000000204', '00000000-0000-4000-8000-000000000013'),
  ('00000000-0000-4000-8000-000000000205', '00000000-0000-4000-8000-000000000003'),
  ('00000000-0000-4000-8000-000000000205', '00000000-0000-4000-8000-000000000008'),
  ('00000000-0000-4000-8000-000000000205', '00000000-0000-4000-8000-000000000012'),
  ('00000000-0000-4000-8000-000000000205', '00000000-0000-4000-8000-000000000006'),
  ('00000000-0000-4000-8000-000000000205', '00000000-0000-4000-8000-000000000004'),
  ('00000000-0000-4000-8000-000000000205', '00000000-0000-4000-8000-000000000014'),
  ('00000000-0000-4000-8000-000000000206', '00000000-0000-4000-8000-000000000010'),
  ('00000000-0000-4000-8000-000000000206', '00000000-0000-4000-8000-000000000004'),
  ('00000000-0000-4000-8000-000000000207', '00000000-0000-4000-8000-000000000002'),
  ('00000000-0000-4000-8000-000000000207', '00000000-0000-4000-8000-000000000005'),
  ('00000000-0000-4000-8000-000000000207', '00000000-0000-4000-8000-000000000013'),
  ('00000000-0000-4000-8000-000000000207', '00000000-0000-4000-8000-000000000006'),
  ('00000000-0000-4000-8000-000000000208', '00000000-0000-4000-8000-000000000009'),
  ('00000000-0000-4000-8000-000000000208', '00000000-0000-4000-8000-000000000001'),
  ('00000000-0000-4000-8000-000000000209', '00000000-0000-4000-8000-000000000011'),
  ('00000000-0000-4000-8000-000000000209', '00000000-0000-4000-8000-000000000004'),
  ('00000000-0000-4000-8000-000000000209', '00000000-0000-4000-8000-000000000008'),
  ('00000000-0000-4000-8000-000000000210', '00000000-0000-4000-8000-000000000005')
on conflict do nothing;

commit;
